### ISSUE TITLE
Error messages after Java update

### ISSUE THREAD

**Issue by Eaterhnk** [volkerrichert/ioBroker.ecotouch#3]
I've been using the script for a long time and it delivered all the values without any problems. However, after one of the last Java updates I keep getting these warnings or error messages, is anything already known?:

error messages:
javascript.0
2023-03-16 21:24:00.043	error	StatusCodeError: 500 - "#E_RE-LOGIN_ATTEMPT\n" at new StatusCodeError (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request-promise-core/lib/errors.js:32:15) at Request.plumbing.callback (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request-promise-core/lib/plumbing.js:104:33) at Request.RP$callback [as _callback] (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request-promise-core/lib/plumbing.js:46:31) at Request.self.callback (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:185:22) at Request.emit (node:events:513:28) at Request.emit (node:domain:489:12) at Request.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:1154:10) at Request.emit (node:events:513:28) at Request.emit (node:domain:489:12) at IncomingMessage.<anonymous> (/opt/iobroker/node_modules/iobroker.javascript/node_modules/request/request.js:1076:12) at Object.onceWrapper (node:events:627:28) at IncomingMessage.emit (node:events:525:35) at IncomingMessage.emit (node:domain:489:12) at endReadableNT (node:internal/streams/readable:1358:12) at processTicksAndRejections (node:internal/process/task_queues:83:21)

javascript.0
2023-03-16 21:24:00.042	error	Error: 500 - "#E_RE-LOGIN_ATTEMPT\n"

javascript.0
2023-03-16 21:24:00.042	error	An error happened which is most likely from one of your scripts, but the originating script could not be detected.

warnings:
2023-03-16 00:01:00.233 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkoƩe.state_sourcepump" not found
2023-03-16 00:01:00.234 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.235 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:66:33
2023-03-16 00:01:00.235 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.235 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:63:37
2023-03-16 00:01:00.235 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.235 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.Waterkotte:54:45)
2023-03-16 00:01:00.235 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkoƩe.state_heaƟngpump" not found
2023-03-16 00:01:00.236 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.236 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:66:33
2023-03-16 00:01:00.236 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.236 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:63:37
2023-03-16 00:01:00.237 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.237 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.WaterkoƩe:54:45)
2023-03-16 00:01:00.237 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkoƩe.state_evd" not found
2023-03-16 00:01:00.241 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.244 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.Waterkotte:66:33
2023-03-16 00:01:00.244 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.244 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:63:37
2023-03-16 00:01:00.244 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.244 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.WaterkoƩe:54:45)
2023-03-16 00:01:00.244 -   [33mwarn  [39m: javascript.0 (1867) State "javascript.0.waterkoƩe.state_compressor1" not found
2023-03-16 00:01:00.245 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.245 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:66:33
2023-03-16 00:01:00.245 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.245 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.Waterkotte:63:37
2023-03-16 00:01:00.245 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.246 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.Waterkotte:54:45)
2023-03-16 00:01:00.246 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkoƩe.state_compressor2" not found
2023-03-16 00:01:00.246 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.247 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.Waterkotte:66:33
2023-03-16 00:01:00.247 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.247 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:63:37
2023-03-16 00:01:00.247 -   [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)  
2023-03-16 00:01:00.247 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.WaterkoƩe:54:45)
2023-03-16 00:01:00.247 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkotte.state_extheater" not found
2023-03-16 00:01:00.248 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.248 -   [33mwarn  [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:66:33
2023-03-16 00:01:00.248 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.248 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.Waterkotte:63:37
2023-03-16 00:01:00.248 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.248 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.Waterkotte:54:45)
2023-03-16 00:01:00.249 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkoƩe.state_alarm" not found
2023-03-16 00:01:00.249 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.257 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:66:33
2023-03-16 00:01:00.257 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.257 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:63:37
2023-03-16 00:01:00.257 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.257 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.Waterkotte:54:45)
2023-03-16 00:01:00.258 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkoƩe.state_cooling" not found
2023-03-16 00:01:00.258 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.258 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:66:33
2023-03-16 00:01:00.258 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.259 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:63:37
2023-03-16 00:01:00.259 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.259 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.WaterkoƩe:54:45)
2023-03-16 00:01:00.259 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkotte.state_water" not found
2023-03-16 00:01:00.260 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.260 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:66:33
2023-03-16 00:01:00.260 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.260 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.Waterkotte:63:37
2023-03-16 00:01:00.260 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.260 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.Waterkotte:54:45)
2023-03-16 00:01:00.260 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkoƩe.state_pool" not found
2023-03-16 00:01:00.261 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.261 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:66:33
2023-03-16 00:01:00.261 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.261 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:63:37
2023-03-16 00:01:00.262 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.262 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.WaterkoƩe:54:45)
2023-03-16 00:01:00.262 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkoƩe.state_solar" not found
2023-03-16 00:01:00.269 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.269 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:66:33
2023-03-16 00:01:00.269 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.269 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.WaterkoƩe:63:37
2023-03-16 00:01:00.270 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.270 -     [33mwarn [39m: javascript.0 (1867) at Request._rp_callbackOrig (script.js.Skrypte_in_Betrieb.WaterkoƩe:54:45)
2023-03-16 00:01:00.270 -     [33mwarn [39m: javascript.0 (1867) State "javascript.0.waterkotte.state_cooling4way" not found
2023-03-16 00:01:00.272 -     [33mwarn [39m: javascript.0 (1867) at setState (/opt/iobroker/node_modules/iobroker.javascript/lib/sandbox.js:1719:20)
2023-03-16 00:01:00.273 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.Waterkotte:66:33
2023-03-16 00:01:00.273 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)
2023-03-16 00:01:00.273 -     [33mwarn [39m: javascript.0 (1867) at script.js.Skrypte_in_Betrieb.Waterkotte:63:37
2023-03-16 00:01:00.273 -     [33mwarn [39m: javascript.0 (1867) at Array.forEach (<anonymous>)

**Comment by volkerrichert** [comment]
Which Java update?

**Comment by Eaterhnk** [comment]
Unfortunately I can't say that exactly, I think it must have been 1-2 years ago and I deactivated this script and I'm only now dealing with it again
